services:
  app:
    container_name: app-ddd
    build: .
    command: tail -f /dev/null
    ports:
      - 3000:5000
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - app-network

  postgres:
    container_name: pg-ddd
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ddd
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: